import type { Metadata } from "next";
import localFont from "next/font/local";
import { ViewTransitions } from "next-view-transitions";
import "./globals.css";

const theboldFont = localFont({
  src: [
    {
      path: "../../public/fonts/the_bold_font.woff",
      // weight: "200",
      style: "normal",
    }
  ],
  variable: "--font-theboldfont",
  display: "swap",
});

const euclidFont = localFont({
  src: [
    {
      path: "../../public/fonts/Euclid Circular A Light.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Euclid Circular A Regular.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Euclid Circular A Medium.ttf",
      weight: "600",
      style: "italic",
    },
    {
      path: "../../public/fonts/Euclid Circular A Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-euclid",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body
          className={`${theboldFont.variable} ${euclidFont.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </ViewTransitions>
  );
}
